#pragma once

#define RF_MESSAGE_PAYLOAD_LENGTH 4

#define RF_MESSAGE_ID_START_PUMP 0x4D
#define RF_MESSAGE_ID_PUMP_FINISHED 0x4E

#define RF_MESSAGE_ID_REQUEST_HUMIDITY 0x4F
#define RF_MESSAGE_ID_RESPOND_HUMIDITY 0x50

#define RF_MESSAGE_ID_REQUEST_LUMINOSITY 0x51
#define RF_MESSAGE_ID_RESPOND_LUMINOSITY 0x52

#define RF_MESSAGE_ID_REQUEST_TEMPERATURE 0x53
#define RF_MESSAGE_ID_RESPOND_TEMPERATURE 0x54

#define RF_MESSAGE_ID_REQUEST_SANITY 0x55
#define RF_MESSAGE_ID_RESPOND_SANITY 0x56
