ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino

USER_LIB_PATH = /home/thiagolobo/arduino_libraries
#ARDUINO_LIBS = RF24 RF24Mesh RF24Network 
BOARD_TAG    = nano328
MONITOR_PORT = /dev/ttyUSB*

include /usr/share/arduino/Arduino.mk
